### ISSUE TITLE
for consideration pl

### ISSUE THREAD

**Issue by ssekar-in** [Valdecy/Metaheuristic-Whale_Optimization_Algorithm#1]
Line number 64 and line 67 in the code may be applied with np.clip. When I tired eggholder function there were issues. I corrected using the above suggestion. 
I am new to github. So pardon if I am using it wrongly.

**Comment by Valdecy** [comment]
You're right! Thank you, I have corrected the code!

**Comment by ssekar-in** [comment]
Welcome! Thank you for sharing.
